"""
🎯 NSE TOP 1000 STOCKS - LIVE RANKED
Auto-generated by fetch_nse_top_500.py
Ranked by Market Capitalization

Generated: 2025-12-11 21:25:36
"""

from datetime import datetime

# Generation timestamp
GENERATED_DATE = "2025-12-11 21:25:36"

# Top 1000 NSE stocks (ranked by market cap)
NSE_TOP_1000 = [
    'RELIANCE.NS',  # 1. ₹2,090,844 Cr
]

# Quick stats
TOTAL_STOCKS = len(NSE_TOP_1000)
TOP_10_MARKET_CAP = 1027813.45  # Top 10 avg market cap (Cr)
TOP_100_MARKET_CAP = 283103.88  # Top 100 avg market cap (Cr)

def get_top_n(n: int = 1000):
    """Get top N stocks"""
    return NSE_TOP_1000[:n]

def get_top_100():
    """Get top 100 large caps"""
    return NSE_TOP_1000[:100]

def get_mid_caps():
    """Get mid caps (101-500)"""
    return NSE_TOP_1000[100:500]

def get_small_caps():
    """Get small caps (501-1000)"""
    return NSE_TOP_1000[500:1000]
