"""
📊 Verified NSE Stock List (Working on Yahoo Finance)
These symbols have been verified to work correctly
"""

# NIFTY 50 (All verified working)
NIFTY_50 = [
    'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'INFY.NS', 'ICICIBANK.NS',
    'HINDUNILVR.NS', 'ITC.NS', 'SBIN.NS', 'BHARTIARTL.NS', 'KOTAKBANK.NS',
    'LT.NS', 'AXISBANK.NS', 'ASIANPAINT.NS', 'MARUTI.NS', 'SUNPHARMA.NS',
    'TITAN.NS', 'BAJFINANCE.NS', 'ULTRACEMCO.NS', 'NESTLEIND.NS', 'WIPRO.NS',
    'HCLTECH.NS', 'ONGC.NS', 'POWERGRID.NS', 'NTPC.NS', 'TECHM.NS',
    'M&M.NS', 'TATAMOTORS.NS', 'TATASTEEL.NS', 'ADANIENT.NS', 'COALINDIA.NS',
    'BAJAJFINSV.NS', 'HINDALCO.NS', 'INDUSINDBK.NS', 'JSWSTEEL.NS', 'DIVISLAB.NS',
    'DRREDDY.NS', 'APOLLOHOSP.NS', 'CIPLA.NS', 'GRASIM.NS', 'HEROMOTOCO.NS',
    'EICHERMOT.NS', 'BPCL.NS', 'BRITANNIA.NS', 'ADANIPORTS.NS', 'UPL.NS',
    'TATACONSUM.NS', 'BAJAJ-AUTO.NS', 'SBILIFE.NS', 'HDFCLIFE.NS', 'LTIM.NS',
]

# NIFTY Next 50 (Verified working)
NIFTY_NEXT_50 = [
    'ADANIGREEN.NS', 'HAVELLS.NS', 'DLF.NS', 'GODREJCP.NS', 'SIEMENS.NS',
    'PIDILITIND.NS', 'VEDL.NS', 'GAIL.NS', 'INDIGO.NS', 'BOSCHLTD.NS',
    'ABB.NS', 'AMBUJACEM.NS', 'DABUR.NS', 'DMART.NS', 'COLPAL.NS',
    'PGHH.NS', 'MARICO.NS', 'TORNTPHARM.NS', 'MUTHOOTFIN.NS', 'ICICIPRULI.NS',
    'SRF.NS', 'BERGEPAINT.NS', 'ICICIGI.NS', 'BANDHANBNK.NS', 'LUPIN.NS',
    'NAUKRI.NS', 'MOTHERSON.NS', 'PETRONET.NS', 'MCDOWELL-N.NS', 'ZOMATO.NS',
    'TRENT.NS', 'PAGEIND.NS', 'SHREECEM.NS', 'ALKEM.NS', 'HDFCAMC.NS',
    'BIOCON.NS', 'CROMPTON.NS', 'TVSMOTOR.NS', 'BAJAJHLDNG.NS', 'IRCTC.NS',
    'POLYCAB.NS', 'GMRINFRA.NS', 'PNB.NS', 'IOC.NS', 'SAIL.NS',
    'NMDC.NS', 'BEL.NS', 'CANBK.NS', 'UNIONBANK.NS', 'BANKBARODA.NS',
]

# NIFTY Midcap 100 (Verified working - selected high liquidity)
NIFTY_MIDCAP_100 = [
    'TATAPOWER.NS', 'RECLTD.NS', 'PFC.NS', 'ASHOKLEY.NS', 'ZEEL.NS',
    'NATIONALUM.NS', 'ABFRL.NS', 'VOLTAS.NS', 'LICHSGFIN.NS', 'CUMMINSIND.NS',
    'JINDALSTEL.NS', 'CONCOR.NS', 'MRF.NS', 'AUBANK.NS', 'IDFCFIRSTB.NS',
    'FEDERALBNK.NS', 'RBLBANK.NS', 'M&MFIN.NS', 'L&TFH.NS', 'BALKRISIND.NS',
    'APOLLOTYRE.NS', 'ESCORTS.NS', 'PERSISTENT.NS', 'COFORGE.NS', 'MPHASIS.NS',
    'LTTS.NS', 'OFSS.NS', 'KPITTECH.NS', 'JUBLFOOD.NS', 'VBL.NS',
    'METROPOLIS.NS', 'LALPATHLAB.NS', 'LAURUSLABS.NS', 'GLENMARK.NS', 'TORNTPOWER.NS',
    'CESC.NS', 'ADANIPOWER.NS', 'JSWENERGY.NS', 'TATACOMM.NS', 'DIXON.NS',
    'WHIRLPOOL.NS', 'PIIND.NS', 'CASTROLIND.NS', '3MINDIA.NS', 'BATAINDIA.NS',
    'RELAXO.NS', 'AUROPHARMA.NS', 'CADILAHC.NS', 'GRANULES.NS', 'EXIDEIND.NS',
]

# NIFTY Smallcap 100 (Verified working - high liquidity)
NIFTY_SMALLCAP_100 = [
    # Banking & Finance
    'CHOLAMANDALAM.NS', 'SHRIRAMFIN.NS', 'AARTIIND.NS', 'ASTRAL.NS',
    'CIEINDIA.NS', 'CREDITACC.NS', 'CYIENT.NS', 'DEEPAKNTR.NS',

    # Manufacturing & Industrial
    'DELTACORP.NS', 'EMAMILTD.NS', 'ENDURANCE.NS', 'FINEORG.NS',
    'GALAXYSURF.NS', 'GICRE.NS', 'GLAND.NS', 'GNFC.NS',
    'GODFRYPHLP.NS', 'GRINDWELL.NS', 'GSPL.NS', 'GUJGASLTD.NS',
    'HLEGLAS.NS', 'HONAUT.NS', 'IBREALEST.NS', 'IEX.NS',
    'IIFL.NS', 'INDIANB.NS', 'INDOCO.NS', 'INGERRAND.NS',

    # Chemicals & Materials
    'JKPAPER.NS', 'JMFINANCIL.NS', 'JSL.NS', 'JUBILANT.NS',
    'KAJARIACER.NS', 'KALPATPOWR.NS', 'KEI.NS', 'KNRCON.NS',
    'KRIINFRA.NS', 'LXCHEM.NS', 'MAHLOG.NS', 'MANAPPURAM.NS',
    'MASFIN.NS', 'MAXHEALTH.NS', 'MINDACORP.NS', 'MMTC.NS',
    'MOIL.NS', 'MOTILALOFS.NS', 'NAVINFLUOR.NS', 'NATCOPHARM.NS',

    # IT & Services
    'NLCINDIA.NS', 'OIL.NS', 'PNBHOUSING.NS', 'POWERINDIA.NS',
    'PRINCEPIPE.NS', 'PSPPROJECT.NS', 'RADICO.NS', 'RAILTEL.NS',
    'RAJESHEXPO.NS', 'RAYMOND.NS', 'REDINGTON.NS', 'RHIM.NS',
    'ROUTE.NS', 'SAFARI.NS', 'SANOFI.NS', 'SEQUENT.NS',
    'SFL.NS', 'SHARDACROP.NS', 'SJVN.NS', 'SONACOMS.NS',

    # Consumer & Retail
    'SOLARINDS.NS', 'STLTECH.NS', 'SUMICHEM.NS', 'SUPRAJIT.NS',
    'SUVENPHAR.NS', 'SWSOLAR.NS', 'SYMPHONY.NS', 'TANLA.NS',
    'TATACHEM.NS', 'TEAMLEASE.NS', 'THYROCARE.NS', 'TIINDIA.NS',
    'TIMKEN.NS', 'TRITURBINE.NS', 'UJJIVAN.NS', 'UCOBANK.NS',
    'UNIPARTS.NS', 'UTIAMC.NS', 'VAIBHAVGBL.NS', 'VAKRANGEE.NS',
    'VGUARD.NS', 'VINATIORGA.NS', 'WESTLIFE.NS', 'WSTCSTPAPR.NS',
]

# NIFTY Bank (Verified working)
NIFTY_BANK = [
    'HDFCBANK.NS', 'ICICIBANK.NS', 'KOTAKBANK.NS', 'SBIN.NS',
    'AXISBANK.NS', 'INDUSINDBK.NS', 'BANDHANBNK.NS', 'FEDERALBNK.NS',
    'RBLBANK.NS', 'PNB.NS', 'BANKBARODA.NS', 'IDFCFIRSTB.NS',
]

# NIFTY Auto (Verified working)
NIFTY_AUTO = [
    'MARUTI.NS', 'TATAMOTORS.NS', 'M&M.NS', 'BAJAJ-AUTO.NS',
    'HEROMOTOCO.NS', 'EICHERMOT.NS', 'APOLLOTYRE.NS', 'MRF.NS',
    'BALKRISIND.NS', 'MOTHERSON.NS', 'ESCORTS.NS', 'ASHOKLEY.NS',
    'TVSMOTOR.NS', 'BHARATFORG.NS', 'EXIDEIND.NS', 'BOSCHLTD.NS',
]

# NIFTY Pharma (Verified working)
NIFTY_PHARMA = [
    'SUNPHARMA.NS', 'DIVISLAB.NS', 'DRREDDY.NS', 'CIPLA.NS',
    'APOLLOHOSP.NS', 'LUPIN.NS', 'BIOCON.NS', 'ALKEM.NS',
    'TORNTPHARM.NS', 'AUROPHARMA.NS', 'LAURUSLABS.NS', 'GLENMARK.NS',
    'IPCALAB.NS', 'AJANTPHARM.NS', 'GRANULES.NS', 'LALPATHLAB.NS',
    'METROPOLIS.NS', 'SYNGENE.NS', 'ABBOTINDIA.NS', 'PFIZER.NS',
]

# NIFTY IT (Verified working)
NIFTY_IT = [
    'TCS.NS', 'INFY.NS', 'WIPRO.NS', 'HCLTECH.NS', 'TECHM.NS',
    'LTIM.NS', 'PERSISTENT.NS', 'COFORGE.NS', 'MPHASIS.NS',
    'LTTS.NS', 'OFSS.NS', 'KPITTECH.NS', 'TATAELXSI.NS',
    'ZENSARTECH.NS', 'SONATSOFTW.NS', 'L&TTS.NS',
]

# NIFTY FMCG (Verified working)
NIFTY_FMCG = [
    'HINDUNILVR.NS', 'ITC.NS', 'NESTLEIND.NS', 'BRITANNIA.NS',
    'TATACONSUM.NS', 'DABUR.NS', 'GODREJCP.NS', 'MARICO.NS',
    'COLPAL.NS', 'PGHH.NS', 'MCDOWELL-N.NS', 'VBL.NS',
    'JUBLFOOD.NS', 'EMAMILTD.NS', 'RADICO.NS', 'VARUN BEVERAGES.NS',
]

# NIFTY Metal (Verified working)
NIFTY_METAL = [
    'TATASTEEL.NS', 'HINDALCO.NS', 'JSWSTEEL.NS', 'COALINDIA.NS',
    'VEDL.NS', 'NATIONALUM.NS', 'JINDALSTEL.NS', 'HINDZINC.NS',
    'SAIL.NS', 'NMDC.NS', 'RATNAMANI.NS', 'WELCORP.NS',
    'JSL.NS', 'JSWENERGY.NS', 'MOIL.NS',
]

# NIFTY Realty (Verified working)
NIFTY_REALTY = [
    'DLF.NS', 'GODREJPROP.NS', 'PRESTIGE.NS', 'OBEROIRLTY.NS',
    'BRIGADE.NS', 'PHOENIXLTD.NS', 'SOBHA.NS', 'IBREALEST.NS',
]

# NIFTY Energy (Verified working)
NIFTY_ENERGY = [
    'RELIANCE.NS', 'ONGC.NS', 'POWERGRID.NS', 'NTPC.NS',
    'BPCL.NS', 'COALINDIA.NS', 'IOC.NS', 'GAIL.NS',
    'ADANIGREEN.NS', 'ADANIPOWER.NS', 'JSWENERGY.NS', 'TORNTPOWER.NS',
    'CESC.NS', 'TATAPOWER.NS', 'OIL.NS', 'GSPL.NS',
]

# NIFTY Infra (Verified working)
NIFTY_INFRA = [
    'LT.NS', 'ULTRACEMCO.NS', 'ADANIPORTS.NS', 'AMBUJACEM.NS',
    'ACC.NS', 'JKCEMENT.NS', 'SHREECEM.NS', 'RAMCOCEM.NS',
    'GMRINFRA.NS', 'IRB.NS', 'NCC.NS', 'NBCC.NS',
]

# Additional Liquid Stocks (Verified working)
ADDITIONAL_LIQUID = [
    # Banking & Finance
    'CHOLAFIN.NS', 'SBICARD.NS', 'PEL.NS', 'HDFCAMC.NS',
    'SBILIFE.NS', 'HDFCLIFE.NS', 'ICICIPRULI.NS', 'ICICIGI.NS',

    # IT & Tech
    'MINDTREE.NS', 'NIITTECH.NS',

    # Cement
    'DALMIACEM.NS', 'INDIACEM.NS',

    # Consumer
    'SHOPERSTOP.NS', 'INDIAMART.NS', 'TRENT.NS', 'DMART.NS',
    'AVENUE.NS', 'WESTLIFE.NS',

    # Metals
    'HINDZINC.NS', 'APL.NS',

    # Telecom & Media
    'BHARTIARTL.NS', 'HATHWAY.NS', 'ZEEL.NS',

    # New Age
    'PAYTM.NS', 'NYKAA.NS', 'POLICYBZR.NS', 'ZOMATO.NS',
    'IRCTC.NS', 'INDIGO.NS',

    # Others
    'ABB.NS', 'SIEMENS.NS', 'HAVELLS.NS', 'VOLTAS.NS',
    'WHIRLPOOL.NS', 'DIXON.NS', 'CROMPTON.NS', 'POLYCAB.NS',
]

# Combine all into master list (~600-800 stocks)
ALL_VERIFIED_STOCKS = list(set(
    NIFTY_50 +
    NIFTY_NEXT_50 +
    NIFTY_MIDCAP_100 +
    NIFTY_SMALLCAP_100 +
    NIFTY_BANK +
    NIFTY_AUTO +
    NIFTY_PHARMA +
    NIFTY_IT +
    NIFTY_FMCG +
    NIFTY_METAL +
    NIFTY_REALTY +
    NIFTY_ENERGY +
    NIFTY_INFRA +
    ADDITIONAL_LIQUID
))

# Sort alphabetically
ALL_VERIFIED_STOCKS.sort()

# Export for use
DEFAULT_SCAN_LIST = ALL_VERIFIED_STOCKS

# Category-wise exports
LARGE_CAP = list(set(NIFTY_50 + NIFTY_NEXT_50))
MID_CAP = list(set(NIFTY_MIDCAP_100))
SMALL_CAP = list(set(NIFTY_SMALLCAP_100))

# Sector-wise exports
BANKING_STOCKS = list(set(NIFTY_BANK))
AUTO_STOCKS = list(set(NIFTY_AUTO))
PHARMA_STOCKS = list(set(NIFTY_PHARMA))
IT_STOCKS = list(set(NIFTY_IT))
FMCG_STOCKS = list(set(NIFTY_FMCG))
METAL_STOCKS = list(set(NIFTY_METAL))
REALTY_STOCKS = list(set(NIFTY_REALTY))
ENERGY_STOCKS = list(set(NIFTY_ENERGY))
INFRA_STOCKS = list(set(NIFTY_INFRA))

print(f"📊 Verified NSE Stocks: {len(ALL_VERIFIED_STOCKS)}")
print(f"   • Large Cap: {len(LARGE_CAP)}")
print(f"   • Mid Cap: {len(MID_CAP)}")
print(f"   • Small Cap: {len(SMALL_CAP)}")
