"""
🎯 NSE TOP 500 STOCKS - LIVE RANKED
Auto-generated by fetch_nse_top_500.py
Ranked by Market Capitalization

This is a PLACEHOLDER file. Run the EOD ranking to generate the real list:
    python main_eod_system.py --mode eod
"""

from datetime import datetime

# Generation timestamp
GENERATED_DATE = "Not generated yet - Run EOD ranking"

# Placeholder - will be replaced by EOD ranking
NSE_TOP_500 = []

def get_top_n(n: int = 500):
    """Get top N stocks"""
    return NSE_TOP_500[:n]

def get_top_100():
    """Get top 100 large caps"""
    return NSE_TOP_500[:100]

def get_mid_caps():
    """Get mid caps (101-300)"""
    return NSE_TOP_500[100:300]

def get_small_caps():
    """Get small caps (301-500)"""
    return NSE_TOP_500[300:500]
