"""
🎯 NSE TOP 500 STOCKS FETCHER
Fetches ALL NSE stocks, ranks by market cap, returns top 500

This runs ONCE per day at market close to generate the top 500 list
for next day's intraday scanning.
"""

import pandas as pd
import yfinance as yf
import time
from typing import List, Dict
import warnings
warnings.filterwarnings('ignore')


def fetch_all_nse_stocks() -> List[str]:
    """
    Fetch ALL NSE stocks from NSE India

    Returns:
        List of NSE stock symbols (e.g., ['RELIANCE.NS', 'TCS.NS', ...])
    """
    print("\n📥 Fetching ALL NSE stocks from NSE India...")

    try:
        # NSE India equity list CSV
        url = "https://archives.nseindia.com/content/equities/EQUITY_L.csv"

        df = pd.read_csv(url)

        # Get symbols
        symbols = df['SYMBOL'].tolist()

        # Filter out non-equity (bonds, warrants, rights)
        equity_symbols = []
        for symbol in symbols:
            # Skip if contains hyphen (rights, warrants)
            if '-' in symbol:
                continue

            # Skip if ends with digit (series, bonds)
            if symbol[-1].isdigit():
                continue

            # Add .NS suffix for Yahoo Finance
            equity_symbols.append(f"{symbol}.NS")

        print(f"✅ Found {len(equity_symbols)} equity stocks")
        return equity_symbols

    except Exception as e:
        print(f"❌ Error fetching NSE stocks: {e}")
        return []


def get_market_cap(symbol: str, max_retries: int = 2) -> float:
    """
    Get market cap for a symbol

    Args:
        symbol: Stock symbol (e.g., 'RELIANCE.NS')
        max_retries: Number of retry attempts

    Returns:
        Market cap in INR (0 if failed)
    """
    for attempt in range(max_retries):
        try:
            if attempt > 0:
                time.sleep(0.5)  # Small delay on retry

            ticker = yf.Ticker(symbol)
            info = ticker.info

            # Try to get market cap
            market_cap = info.get('marketCap', 0)

            if market_cap and market_cap > 0:
                return market_cap

            # Fallback: calculate from price * shares
            price = info.get('currentPrice', 0)
            shares = info.get('sharesOutstanding', 0)

            if price > 0 and shares > 0:
                return price * shares

            return 0

        except Exception:
            if attempt == max_retries - 1:
                return 0
            continue

    return 0


def rank_stocks_by_market_cap(symbols: List[str], batch_size: int = 50) -> List[Dict]:
    """
    Rank stocks by market cap

    Args:
        symbols: List of stock symbols
        batch_size: Number of stocks to process at a time (for progress display)

    Returns:
        List of dicts with 'symbol' and 'market_cap', sorted by market cap (descending)
    """
    print(f"\n📊 Ranking {len(symbols)} stocks by market cap...")
    print("⏳ This will take ~10-15 minutes (fetching market cap for each stock)")

    ranked = []
    failed = 0

    for i, symbol in enumerate(symbols, 1):
        # Get market cap
        market_cap = get_market_cap(symbol)

        if market_cap > 0:
            ranked.append({
                'symbol': symbol,
                'market_cap': market_cap,
                'market_cap_cr': market_cap / 10000000  # Convert to Crores
            })
        else:
            failed += 1

        # Progress update
        if i % batch_size == 0 or i == len(symbols):
            print(f"   Progress: {i}/{len(symbols)} ({i*100//len(symbols)}%) - "
                  f"Ranked: {len(ranked)}, Failed: {failed}")

        # Small delay to avoid API ban (1 request per 0.2s = 5 req/sec)
        time.sleep(0.2)

    # Sort by market cap (descending)
    ranked.sort(key=lambda x: x['market_cap'], reverse=True)

    print(f"\n✅ Successfully ranked {len(ranked)} stocks")
    print(f"⚠️ Failed: {failed} stocks")

    return ranked


def save_top_500(ranked: List[Dict], output_file: str = 'config/nse_top_500_live.py'):
    """
    Save top 500 stocks to Python file

    Args:
        ranked: List of ranked stocks
        output_file: Output file path
    """
    top_500 = ranked[:500]

    print(f"\n💾 Saving Top 500 to {output_file}...")

    # Generate Python code
    code = '''"""
🎯 NSE TOP 500 STOCKS - LIVE RANKED
Auto-generated by fetch_nse_top_500.py
Ranked by Market Capitalization

Generated: {date}
"""

from datetime import datetime

# Generation timestamp
GENERATED_DATE = "{date}"

# Top 500 NSE stocks (ranked by market cap)
NSE_TOP_500 = [
'''.format(date=pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S'))

    # Add stock symbols with comments showing rank and market cap
    for i, stock in enumerate(top_500, 1):
        symbol = stock['symbol']
        market_cap_cr = stock['market_cap_cr']
        code += f"    '{symbol}',  # {i}. ₹{market_cap_cr:,.0f} Cr\n"

    code += ''']

# Quick stats
TOTAL_STOCKS = len(NSE_TOP_500)
TOP_10_MARKET_CAP = {top_10_cap:.2f}  # Top 10 avg market cap (Cr)
TOP_100_MARKET_CAP = {top_100_cap:.2f}  # Top 100 avg market cap (Cr)

def get_top_n(n: int = 500):
    """Get top N stocks"""
    return NSE_TOP_500[:n]

def get_top_100():
    """Get top 100 large caps"""
    return NSE_TOP_500[:100]

def get_mid_caps():
    """Get mid caps (101-300)"""
    return NSE_TOP_500[100:300]

def get_small_caps():
    """Get small caps (301-500)"""
    return NSE_TOP_500[300:500]
'''.format(
        top_10_cap=sum(s['market_cap_cr'] for s in top_500[:10]) / 10,
        top_100_cap=sum(s['market_cap_cr'] for s in top_500[:100]) / 100
    )

    # Write to file
    with open(output_file, 'w') as f:
        f.write(code)

    print(f"✅ Saved!")
    print(f"\n📊 Top 10 Stocks:")
    for i, stock in enumerate(top_500[:10], 1):
        symbol = stock['symbol'].replace('.NS', '')
        market_cap_cr = stock['market_cap_cr']
        print(f"   {i:2d}. {symbol:15s} - ₹{market_cap_cr:>10,.0f} Cr")


def main():
    """Main function"""
    print("="*70)
    print("🎯 NSE TOP 500 STOCKS GENERATOR")
    print("="*70)

    # Step 1: Fetch all NSE stocks
    all_symbols = fetch_all_nse_stocks()

    if not all_symbols:
        print("❌ Failed to fetch NSE stocks")
        return

    # Step 2: Rank by market cap
    ranked = rank_stocks_by_market_cap(all_symbols)

    if len(ranked) < 500:
        print(f"⚠️ Warning: Only {len(ranked)} stocks ranked (less than 500)")

    # Step 3: Save top 500
    save_top_500(ranked)

    print("\n" + "="*70)
    print("✅ TOP 500 LIST GENERATION COMPLETE!")
    print("="*70)
    print("\n💡 Usage:")
    print("   from config.nse_top_500_live import NSE_TOP_500")
    print("   stocks = NSE_TOP_500  # All 500")
    print("   stocks = NSE_TOP_500[:100]  # Top 100 only")


if __name__ == "__main__":
    main()
